### ISSUE TITLE
로고에 들어갈 약 이미지 선정

### ISSUE THREAD

**Issue by yukmj1123** [yhk24356/Open_Source_Programming#10]
1. https://www.flaticon.com/free-icon/medicine_883407?term=medicine&page=1&position=2&page=1&position=2&related_id=883407&origin=search
2. https://www.flaticon.com/free-icon/medicine_656019?term=medicine&page=1&position=1&page=1&position=1&related_id=656019&origin=search

저는 1번이 나은거같은데 2번도 깔끔해서 괜찮은거같아요 어떤걸로할까요?

**Comment by yhk24356** [comment]
전 1번이 좋은 것 같습니다
