### ISSUE TITLE
중복 카테고리 선택 문제

### ISSUE THREAD

**Issue by yukmj1123** [yhk24356/Open_Source_Programming#16]
중복 카테고리 선택을 하려면 db query를 사용해야하는데 남은 시간에 코드합치고 적용하기엔 시간이 좀 빠듯할거같네요 우선 단일 카테고리만 선택가능하게 하고 추후 수정하는 것이 좋을 것 같습니다

**Comment by yhk24356** [comment]
그 편이 프로젝트 완성도 측면에서 나을 것 같습니다.
