### ISSUE TITLE
pr이 안되는 오류가 생겼는데 다시 pr 해주실 수 있으신가요?

### ISSUE THREAD

**Issue by yhk24356** [yhk24356/Open_Source_Programming#18]
프로젝트 이름 때문에 그런가 싶어서 수정해봤습니다.

**Comment by yukmj1123** [comment]
pr이 안된다는게 뭔가요 ?? 자기가 가지고 있는 코드 pr은 본인이 해야해서요...

**Comment by yukmj1123** [comment]
git fetch랑 full받으셨나요 ? 받으신 다음에 pr하셔야돼요

**Comment by yhk24356** [comment]
아 pr 수락 말씀드린거였어요
