### ISSUE TITLE
약 상세정보 html 페이지 피드백 부탁드립니다

### ISSUE THREAD

**Issue by yhk24356** [yhk24356/Open_Source_Programming#21]
페이지에 더 추가할 내용이 있으면 말씀해주시고 디자인 측면에서 피드백 부탁드립니다.

**Comment by yukmj1123** [comment]
추가할 내용없는거같습니다 고생하셨습니다! url연결 도와드리려는데 어느 부분 도와드리면될까요 ?

**Comment by yhk24356** [comment]
리스트 작업하시는 분이 완성되시면 url 연결 하는 방법 알려주실 수 있으신가요?
