### ISSUE TITLE
README파일 작성에 관해서

### ISSUE THREAD

**Issue by yhk24356** [yhk24356/Open_Source_Programming#23]
README 파일에 포함되어야 하는 부분은
1. 설치 방법
2. 의존성 (버전 명시)
3. 실행 방법
4. 라이선스, 연락처 등 입니다.

라이선스는 MIT 라이선스를 사용하면 될 것 같고, 나머지 부분은 어떻게 채워야 할까요?

**Comment by yukmj1123** [comment]
설치 방법이랑 실행방법은 저희가 배포를 해야하는데 배포까지 마무리 할 수 있는지 모르겠네요..ㅠㅠ

**Comment by yhk24356** [comment]
> 설치 방법이랑 실행방법은 저희가 배포를 해야하는데 배포까지 마무리 할 수 있는지 모르겠네요..ㅠㅠ

사용자가 장고를 다운로드 받은 후, 저희 저장소를 클론해서 사용할 수 있도록 하면 어떨까요?

**Comment by yukmj1123** [comment]
넵 배포까지 어려우면 그렇게라도 작성해야할것같아요 일단 11시까지 진행한 다음에 프로젝트에 차도가 없으면 그때 그렇게 작성하도록 해요!
