### ISSUE TITLE
저희가 웹사이트를 만들며 더 추가로 만들면 좋을만한 점

### ISSUE THREAD

**Issue by yhk24356** [yhk24356/Open_Source_Programming#27]
자유롭게 적어주시면 좋겠습니다.
전 디자인을 보강하고, 많은 html페이지들을 동적이게 구현하고 싶습니다.

**Comment by Seokjun-Yang** [comment]
증상에 따른 약 목록을 보여주는 페이지의 디자인을 더 보강하고 싶습니다.
