### ISSUE TITLE
앞으로 프로그램의 개선 방향

### ISSUE THREAD

**Issue by yhk24356** [yhk24356/Open_Source_Programming#28]
저는 저희 취지가 편하게 약을 찾을 수 있게 하는 것이므로 시간이 부족하여 하지 못했지만 앱으로 확장해 나갈 수 있으면 좋겠습니다.

**Comment by Seokjun-Yang** [comment]
동감합니다. 사용자가 더 약을 편하게 찾을 수 있도록 시각 디자인을 더 구현해나가고 싶습니다.
