### ISSUE TITLE
역할 분담에 대해

### ISSUE THREAD

**Issue by Seokjun-Yang** [yhk24356/Open_Source_Programming#3]
감기나 복통 등 증상에 따라 필요한 약이 여러가지 있을 것입니다.
각자 증상을 선택해서 역할을 분담한 다음 증상에 필요한 약에 대해 조사해보는게 어떨까요?

**Comment by yhk24356** [comment]
그러면 제가 두통과 근육통에 관련된 약에 대해서 조사하겠습니다

**Comment by yukmj1123** [comment]
좋습니다 각자 분담해서 조사한뒤에 제가 데이터 전처리 과정 맡을게요 그 뒤에 각자 페이지별로 맡아서 구현하면 좋을 것 같습니다!
