### ISSUE TITLE
리스트페이지와 상세페이지 연결

### ISSUE THREAD

**Issue by yukmj1123** [yhk24356/Open_Source_Programming#30]
리스트페이지와 상세페이지 연결은 시간내에 하지못할 것 같아서 발표전 따로 수정하는게 나을것같습니다

**Comment by yhk24356** [comment]
네 알겠습니다. 그래도 콜드원에스시럽 하나는 연결했어요

**Comment by yhk24356** [comment]
그걸로 발표하면 될 것 같아요
