### ISSUE TITLE
기능(페이지) 별 역할 분담

### ISSUE THREAD

**Issue by yukmj1123** [yhk24356/Open_Source_Programming#4]
1. 카테고리를 선택하는 웹페이지
2. 선택 후 연관 된 약의 리스트들을 보여주는 페이지
3. 약을 클릭하면 상세 정보를 보여주는 페이지

이렇게 나눌 수 있는것 같은데 제가 1번 맡겠습니다~ 
하고 싶은 페이지 있으실까요?

**Comment by Seokjun-Yang** [comment]
그럼 제가 2번을 맡도록 하겠습니다

**Comment by yhk24356** [comment]
제가 3번 맡도록 하겠습니다
