### ISSUE TITLE
웹사이트의 글꼴 설정에 대하여

### ISSUE THREAD

**Issue by yhk24356** [yhk24356/Open_Source_Programming#5]
웹페이지를 만들 때 어떤 글꼴을 사용하는 것이 좋을까요?

**Comment by Seokjun-Yang** [comment]
한글에 HY엽서M이라는 글꼴이 있는데 혹시 어떠신가요?

**Comment by yukmj1123** [comment]
우선 기본폰트로 구현한다음 디자인 하는것이 어떨까요 ?

**Comment by yhk24356** [comment]
글꼴은 좋은 것 같아요! 그런데 적용하는 과정에서 오류가 나서 일단 기본 폰트로 구현했습니다.
