### ISSUE TITLE
구현 현황에 대하여

### ISSUE THREAD

**Issue by yukmj1123** [yhk24356/Open_Source_Programming#6]
혹시 각자 맡으신 부분 어디까지 구현하셨을까요 ? 저는 필요한 데이터 수집을 더 진행했습니다

**Comment by yhk24356** [comment]
기초 html 디자인을 마쳤고, 사진과 약의 정보를 수집하여 작성하면 될 것 같습니다.

**Comment by Seokjun-Yang** [comment]
사전에 수집했던 약 종류에 따라 화면에 쓰일 약 및 파스 사진들을 수집했습니다
