### ISSUE TITLE
상세 페이지 구현에 넣을 url 조사가 필요할거같습니다.

### ISSUE THREAD

**Issue by yukmj1123** [yhk24356/Open_Source_Programming#7]
상세페이지 구현에 약 공식홈페이지 url을 입력하기로했는데 조사가 필요할것같습니다
나눠서 할까요 ?

**Comment by yhk24356** [comment]
처음 약 명을 나눈 것처럼 조사하면 어떨까요?

**Comment by Seokjun-Yang** [comment]
증상에 따라 조사하는게 좋을거같아요
전에 약 조사했을 때 남겨둔 출처도 참고하시면 좋을거 같습니다
